apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yq-helm-chart-version
  labels:
    app.kubernetes.io/version: "0.1"
spec:
  workspaces:
    - name: source
      description: A workspace that contains the file which needs to be altered.
  params:
    - name: appVersion
      type: string
    - name: imageTag
      type: string
    - name: chartDir
      type: string
    - name: image
      type: string
      description: The yq image to use.
      default: docker.io/mikefarah/yq:4.16.2@sha256:0d4f6e27bdcac7316f635acd524ab0eecc4ad50834b54d10322268650c7712cb
  steps:
    - name: replace-in-yaml
      image: $(params.image)
      workingDir: $(workspaces.source.path)/$(params.chartDir)
      securityContext:
        runAsUser: 0
      script: |
        /usr/bin/env sh
        set -e

        /usr/bin/yq e -i '.appVersion="$(params.appVersion)"' Chart.yaml
        /usr/bin/yq e -i '.image.tag="$(params.imageTag)"' values.yaml
