---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: general-kaniko-pipeline-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: gitsubmodules
    default: "false"
  - name: registryrepo
    default: registry.solarfs.io
  - name: project
  - name: appname
  - name: apptype
    default: "server"
  - name: pipelineRef
    default: "general-kaniko"
  - name: chartgitrepositoryurl
  - name: chartgitbranch
    default: dev
  - name: chartcontext
    default: "."
  - name: dockerfile
    default: "./Dockerfile"
  - name: context
    default: "."
  - name: buildimage
    default: "gcr.io/kaniko-project/executor:v1.9.1-debug"
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      labels:
        tekton.dev/pipeline: general-kaniko
        tekton.dev/project: $(tt.params.project)
        tekton.dev/appname: $(tt.params.appname)
      generateName: $(tt.params.appname)-$(tt.params.pipelineRef)- # 前缀名称 
      namespace: tekton-pipelines
    spec:
      workspaces:
        - name: source-ws
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              storageClassName: local-path
              resources:
                requests:
                  storage: 1Gi
        - name: chart-source-ws
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              storageClassName: local-path
              resources:
                requests:
                  storage: 1Gi
        - name: cache-ws
          persistentVolumeClaim:
            claimName: tekton-cache-claim
          subPath: cache-tekton-$(tt.params.project)-$(tt.params.appname)
        - name: dockerconfig-ws
          secret:
            secretName: pld-cicd-secret
        - name: basic-auth-ws
          secret:
            secretName: gitlab-basic-auth-secret
        - name: chart-basic-auth-ws
          secret:
            secretName: gitlab-basic-auth-secret
      params:
      - name: SOURCE_URL
        value: $(tt.params.gitrepositoryurl)
      - name: SOURCE_REFERENCE
        value: $(tt.params.gitrevision)
      - name: SOURCE_SUBMODULES
        value: $(tt.params.gitsubmodules)
      - name: CHART_SOURCE_URL
        value: $(tt.params.chartgitrepositoryurl)
      - name: CHART_SOURCE_BRANCH
        value: $(tt.params.chartgitbranch)
      - name: CHART_CONTEXT
        value: $(tt.params.chartcontext)

      - name: APP_NAME
        value: $(tt.params.appname)
      - name: APP_TYPE
        value: $(tt.params.apptype)
      - name: IMAGE_URL
        value: $(tt.params.registryrepo)/$(tt.params.project)/$(tt.params.appname)
      - name: IMAGE_TAG
        value: $(tt.params.gitrevision)

      - name: BUILDER_IMAGE
        value: "$(tt.params.buildimage)"
      - name: DOCKERFILE
        value: "$(tt.params.dockerfile)"
      - name: CONTEXT
        value: "$(tt.params.context)"

      - name: DELETE_PIPELINERUNS_SELECTOR
        value: 'tekton.dev/project=$(tt.params.project),tekton.dev/appname=$(tt.params.appname)'
      - name: CHART_SOURCE_URL
        value: $(tt.params.chartgitrepositoryurl)
      - name: CHART_SOURCE_BRANCH
        value: $(tt.params.chartgitbranch)
      pipelineRef:
        name: $(tt.params.pipelineRef)
      serviceAccountName: tekton-triggers-sa
      timeout: 15m0s
