---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: unit-testing-pipeline-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: project
  - name: appname
  - name: envs
    description: The envs, Example a=1|b=2
    default: ""
  - name: imageurl
  - name: imagetag
    default: latest
  - name: command
  - name: pipelineRef
    default: "unit-testing"
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      labels:
        tekton.dev/pipeline: $(tt.params.pipelineRef)
        tekton.dev/project: $(tt.params.project)
        tekton.dev/appname: $(tt.params.appname)
      generateName: $(tt.params.pipelineRef)-$(tt.params.project)-$(tt.params.appname)- # 前缀名称 
      namespace: tekton-pipelines
    spec:
      workspaces:
        - name: source-ws
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              storageClassName: local-path
              resources:
                requests:
                  storage: 1Gi
        - name: cache-ws
          persistentVolumeClaim:
            claimName: tekton-cache-claim
          subPath: cache-tekton-$(tt.params.pipelineRef)
        - name: basic-auth-ws
          secret:
            secretName: gitlab-basic-auth-secret
      params:
      - name: SOURCE_URL
        value: $(tt.params.gitrepositoryurl)
      - name: SOURCE_REFERENCE
        value: $(tt.params.gitrevision)
      - name: ENVS
        value: $(tt.params.envs)
      - name: IMAGE_URL
        value: $(tt.params.imageurl)
      - name: IMAGE_TAG
        value: $(tt.params.imagetag)
      - name: COMMAND
        value: $(tt.params.command)
      pipelineRef:
        name: $(tt.params.pipelineRef)
      serviceAccountName: tekton-triggers-sa
      timeout: 10m0s
      podTemplate:
        imagePullSecrets:
          - name: registry-pld-cicd
